In [1]:
# 4. Linear Algebra

In [6]:
import numpy as np

# Vector Products

In [7]:
#Vector Products
a = np.array([1,2,3])
b = np.array([5,6,7])

#1*5 + 2*6 + 3*7
print("Dot Product: ", np.dot(a, b))

# (2*7 - 3*6) - (1*7 -3*5) + 1*6-2*5
print("Cross Product: ", np.cross(a, b))

Dot Product:  38
Cross Product:  [-4  8 -4]


# Matrix 

In [9]:
# Matrix 
m1 = np.matrix([[1,2,3,4], [5,6,7,8], [2,3,4,5], [6,7,8,9]])
print('Matrix:: \n',m1)
m1.shape

Matrix:: 
 [[1 2 3 4]
 [5 6 7 8]
 [2 3 4 5]
 [6 7 8 9]]


(4, 4)

# Matrix Multiplication

In [15]:
m1 = np.matrix([[1,4,5], [2,4,3], [5,6,8]])
print("Matrix m1: \n",m1)

m2 = np.matrix([[2], [4], [5]])
print("Matrix m2: \n",m2)

print('m1 * m2=\n', m1 * m2)

Matrix m1: 
 [[1 4 5]
 [2 4 3]
 [5 6 8]]
Matrix m2: 
 [[2]
 [4]
 [5]]
m1 * m2=
 [[43]
 [35]
 [74]]


# Rank Of Matrix

In [16]:
# Rank of matrix 
# The rank of a matrix is defined as (a) the maximum number of linearly independent column vectors in the matrix 
# or (b) the maximum number of linearly independent row vectors in the matrix.
# https://stattrek.com/matrix-algebra/matrix-rank.aspx

# For Machine Learning, it is always preferred to have most linearly independent vectors.
# Linearly dependent column is the column which can be identified as function between 2 or more columns.
# then this column is not considered in rank.

In [21]:
from numpy import linalg as la

m3 = np.matrix([[1,3,1], [2,2,1], [3,5,3]])
print("m3: \n", m3)
print("Rank of m3 is:\n", "la.matrix_rank(m3)::" , la.matrix_rank(m3))

m3: 
 [[1 3 1]
 [2 2 1]
 [3 5 3]]
Rank of m3 is:
 la.matrix_rank(m3):: 3


# Determinent of Matrix

In [25]:
# A = [[a,b][c,d]]
# then det(A) = a*d - b*c

# B = [a, b, c]
#     [d, e, f]
#     [g, h, i]
# then det(B) = a * det([[e,f], [h,i]]) - b * det([[d,f], [g,i]]) + c*det([[d,e], [g,h]])
#             = a * (ei-fh) - b * (di - fg) + c * (dh - eg) 

# Inverse of Matrix

In [24]:

# A  * A^-1 = I (i.e. Identity Matrix)

#""" 
#    | a  b | ^-1         1/(ad-bc)| d  -b | 
#    | c  d |         =            |-c   a |
#"""

# 1. Inverse of matrix only exists if all of columns are linearly independent.
# 2. Inverse of matrix only exists if no element in diagonal is 0.
# [A * B]^-1 = B^-1 * A^-1
# [A * B * C * D]^-1 = D ^-1 * C^-1 * B^-1 * A^-1