# Numpy Basics

In [1]:
# Most commonly used library for Data Science
# NUMerical PYthon
# Used for scientific omputing and data analysis

#Basic numpy object: ndarray i.e. n-dimensional Array 
# this is homogeneous array i.e. it contains elements with same datatype

#Why Numpy
    # Fast. Programmed in C. Parallel operations
    # Convenient

In [2]:
import numpy as np

#Single dim array
a = np.array([1,2,3])
print(a)

#2-dim array
b = np.array([[1,2,3], [4,5,6]])
print(b)

#dimensions of array
print("a.shape::",a.shape)
print("b.shape::",b.shape)

#checking data type of elements in array
print("b.dtype::", b.dtype)

#Number of rows present in array
print("no. of rows:: b.ndim::",b.ndim)

print("type(a)::", type(a))

#arange function. similar to range in python
print("np.arange(10)::", np.arange(10))

[1 2 3]
[[1 2 3]
 [4 5 6]]
a.shape:: (3,)
b.shape:: (2, 3)
b.dtype:: int32
no. of rows:: b.ndim:: 2
type(a):: <class 'numpy.ndarray'>
np.arange(10):: [0 1 2 3 4 5 6 7 8 9]


In [3]:
# Speed Test 1 for numpy

#for Python list
c = range(10000)

%timeit [ i ** 3 for i in c]

#for numpy array
np_c = np.arange(10000)
%timeit np_c ** 3

5.53 ms ± 56.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
26.5 µs ± 395 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [4]:
# Speed Test 2 for numpy

#for Python list
l1 = range(10000)
l2 = [i **2 for i in range(10000)]

%timeit list(map(lambda x,y : x * y, l1, l2))


#for numpy array
np_c1 = np.array(l1)
np_c2 = np.array(l2)
%timeit np_c1 * np_c2

1.71 ms ± 6.08 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
9.35 µs ± 138 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
#np arange usage with starting element upto last element-1
np.arange(2,14)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [6]:
#np arange usage with starting element and increment step

np.arange(2,14,3)

array([ 2,  5,  8, 11])

In [7]:
#Array with 0
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
#Array with 1
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
#Identity matrix. i.e. matrix with all diagonal elements are 1 and others are 0

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
# Full array fill with number
np.full((2,3), 4.4)

array([[4.4, 4.4, 4.4],
       [4.4, 4.4, 4.4]])

In [11]:
#Full array fill with decimal number with type specified
np.full((2,3), 4.4, dtype=np.int)

array([[4, 4, 4],
       [4, 4, 4]])

In [12]:
#fill all diagonal entries with numbers specified
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [5]:
#Tile Function. duplicates a row in array
v = np.array([1,2,4])
print("np.tile(v, (3, 1))\n", np.tile(v, (3, 1)))

print("\nnp.tile(v, (3,2))\n",np.tile(v, (3,2)))

np.tile(v, (3, 1))
 [[1 2 4]
 [1 2 4]
 [1 2 4]]

np.tile(v, (3,2))
 [[1 2 4 1 2 4]
 [1 2 4 1 2 4]
 [1 2 4 1 2 4]]


In [14]:
# Random number generation
print(np.random.random())

print("Random number from 2 to 50::", np.random.random() * 50 + 2)
print("Random int from 2 to 50::", np.random.randint(50) )

#array with random numbers
randomArr = np.random.random([3,3])
print(randomArr)


0.31054787544871143
Random number from 2 to 50:: 22.871015397748298
Random int from 2 to 50:: 0
[[0.2961001  0.48866508 0.69887019]
 [0.79017563 0.43630046 0.33328964]
 [0.03013496 0.24082    0.44245725]]


In [15]:
#linspace function. gives numbers in specified range in equal intervals.
#Similar to seq function in R.
a = np.linspace(0,50, 100)
print(a)

#size of np array
print("a.itemsize:::",a.itemsize)

[ 0.          0.50505051  1.01010101  1.51515152  2.02020202  2.52525253
  3.03030303  3.53535354  4.04040404  4.54545455  5.05050505  5.55555556
  6.06060606  6.56565657  7.07070707  7.57575758  8.08080808  8.58585859
  9.09090909  9.5959596  10.1010101  10.60606061 11.11111111 11.61616162
 12.12121212 12.62626263 13.13131313 13.63636364 14.14141414 14.64646465
 15.15151515 15.65656566 16.16161616 16.66666667 17.17171717 17.67676768
 18.18181818 18.68686869 19.19191919 19.6969697  20.2020202  20.70707071
 21.21212121 21.71717172 22.22222222 22.72727273 23.23232323 23.73737374
 24.24242424 24.74747475 25.25252525 25.75757576 26.26262626 26.76767677
 27.27272727 27.77777778 28.28282828 28.78787879 29.29292929 29.7979798
 30.3030303  30.80808081 31.31313131 31.81818182 32.32323232 32.82828283
 33.33333333 33.83838384 34.34343434 34.84848485 35.35353535 35.85858586
 36.36363636 36.86868687 37.37373737 37.87878788 38.38383838 38.88888889
 39.39393939 39.8989899  40.4040404  40.90909091 41.

In [16]:
# using arange function to create multi-dimensional array
np.arange(18).reshape(2,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [17]:
#if you dont want to do any calculation to compute column numbers, just put -1. np will adjust dimensions automatically
np.arange(18).reshape(2,3, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [3]:
#accessing elements in numpy array
a = np.array([2,4,6,8,10,12,14,16,18])

print("a[0]::", a[0])
print("a[3]::", a[3])
print("a[[2,4,6]]::", a[[2,4,6]])

#subsetting array
print("a[3:]::", a[3:])
print("a[3:7]::", a[3:7])
print("a[3:11]::", a[3:11])  #giving index more than actual elements, will not throw error
print("a[0::2]::", a[0::2])


#accessing elements in multi dim array
b = np.arange(9).reshape(3,3)
print("np.arange(9).reshape(3,3)\n", b)
print("b[1][2]::", b[1][2])
print("b[1,2]::", b[1,2])

#filtering on array
b > 2

b[(b > 2) & (b < 5)]

a[0]:: 2
a[3]:: 8
a[[2,4,6]]:: [ 6 10 14]
a[3:]:: [ 8 10 12 14 16 18]
a[3:7]:: [ 8 10 12 14]
a[3:11]:: [ 8 10 12 14 16 18]
a[0::2]:: [ 2  6 10 14 18]
np.arange(9).reshape(3,3)
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
b[1][2]:: 5
b[1,2]:: 5


array([3, 4])

In [19]:
# numpy arrays are mutable
c = np.arange(10)
d = c
print("c::",c)
print("d::", d)
c[0] = 12
print("updated c::",c)
print("updated d::", d)

#to avoid such situation, use copy of numpy array
e = c.copy()
c[2] = 45
print("e::", e)

#check memory locations same or not??
print("np.shares_memory(c,d)::",np.shares_memory(c,d))
print("np.shares_memory(c,e)::",np.shares_memory(c,e))

c:: [0 1 2 3 4 5 6 7 8 9]
d:: [0 1 2 3 4 5 6 7 8 9]
updated c:: [12  1  2  3  4  5  6  7  8  9]
updated d:: [12  1  2  3  4  5  6  7  8  9]
e:: [12  1  2  3  4  5  6  7  8  9]
np.shares_memory(c,d):: True
np.shares_memory(c,e):: False


In [20]:
#Transpose of array (Matrix)
f = np.array([[1,2,3], [4,5,6]])
print(f)

print("f.T::\n", f.T)

[[1 2 3]
 [4 5 6]]
f.T::
 [[1 4]
 [2 5]
 [3 6]]


In [21]:
# Stacking numpy arrays
g = np.array([[7,8,9], [10,11,12]])

#Vertical Stack
print("np.vstack((f, g)) ::: \n", np.vstack((f, g))) 

#Horizontal Stack
print("np.hstack((f, g)) ::: \n", np.hstack((f, g))) 



np.vstack((f, g)) ::: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
np.hstack((f, g)) ::: 
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [22]:
#numerical operations using numpy arrays
h = np.arange(1,10)
print("h::", h)

#sine operation
print("np.sin(h):: ",np.sin(h))

#cosine operation
print("np.cos(h):: ",np.cos(h))

#exponential function i.e. e^n
print("np.exp(h):: ",np.exp(h))

#sum of all numbers in array
print("np.sum(h):: ",np.sum(h))

#median of all numbers in array
print("np.median(h):: ",np.median(h))

#standard Deviation
print("h.std():: ", h.std())

#Determinent of matrix
i = np.arange(1, 10).reshape((3,3))
print("i::", i)
print("np.linalg.det(i):: ", np.linalg.det(i))

#linalg stands for Linear Algebra

#Column wise sum 
print("i.sum(axis = 0):: ", i.sum(axis = 0))

#Row wise sum 
print("i.sum(axis = 1):: ", i.sum(axis = 1))

#Inverse of matrix
print("np.linalg.inv(i):: ", np.linalg.inv(i))

#Eigen values of matrix
print("np.linalg.eig(i):: ", np.linalg.eig(i))

#Transpose matrix
j = i.T
print("j::", j)

#Dot product of Matric
print("np.dot(i,j)::", np.dot(i,j))

#Max value 
print("i.max()::", i.max())
print("i.argmax()::", i.argmax())

#Sorting numpy array
print("Ascending Orser :: np.sort(h) ::", np.sort(h))

print("DEscending Order:: np.sort(h)[ ::-1]::,", np.sort(h)[::-1])



h:: [1 2 3 4 5 6 7 8 9]
np.sin(h)::  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
np.cos(h)::  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026]
np.exp(h)::  [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
np.sum(h)::  45
np.median(h)::  5.0
h.std()::  2.581988897471611
i:: [[1 2 3]
 [4 5 6]
 [7 8 9]]
np.linalg.det(i)::  6.66133814775094e-16
i.sum(axis = 0)::  [12 15 18]
i.sum(axis = 1)::  [ 6 15 24]
np.linalg.inv(i)::  [[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]
np.linalg.eig(i)::  (array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.6123

In [23]:
#specify data types while creating arrays
b1 = np.array([1,0,1], dtype = bool)
b2 = np.array([1,1,0], dtype = bool)

print("np.logical_or(b1, b2)::", np.logical_or(b1, b2))
print("np.logical_and(b1, b2)::", np.logical_and(b1, b2))
print("b1 == b2::", b1 == b1)
print("np.all(b1 == b1)::", np.all(b1 == b1))



np.logical_or(b1, b2):: [ True  True  True]
np.logical_and(b1, b2):: [ True False False]
b1 == b2:: [ True  True  True]
np.all(b1 == b1):: True


In [ ]:
# Dot Product of v